#!/bin/bash

echo "Warning: using sudo."
sudo wvdial --config="${HOME}/.wvdialrc"

# if [[ $EUID -ne 0 ]]; then
#   echo "You must be a root user" 2>&1
#   exit 1
# else
#   wvdial --config="${HOME}/.wvdialrc"
# fi
